spring:
  application:
    name: Backend
  datasource:
      url: jdbc:mysql://localhost:3306/aqualifelinedb
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mqtt:
  broker:
    url: tcp://10.93.128.211:1883
    client:
      id: SpringBootClient
jwt:
  secret: mysecretkey1234567890mysecretkey1234567890
  expiration: 3600000