spring:
  application:
    name: Backend
  datasource:
    url: jdbc:postgresql://10.93.128.211:5432/aquarium_db # Replace with valid Data
    username: aquarium_admin
    password: Start1234!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mqtt:
  broker:
    url: tcp://10.93.128.211:1883
    client:
      id:SpringBootClient
